title: Per aspera ad astra
description: jynoh00 - development blog

url: https://jynoh00.github.io
# Only necessary when hosting your site in a sub-directory. Project sites hosted on GitHub Pages are the common use-case of this variable.
baseurl: # Ex: /project-page
paginate_path: "blog/page:num/"
permalink: blog/:title/

# Header Option
# header: large

sass:
    style: compressed

markdown: kramdown
highlighter: rouge
plugins: [jekyll-paginate]
paginate: 5   # 홈페이지에 처음 보일 게시글 개수

navigation:
    - title: Home
      url: /index.html
    - title: About
      url: /about
    - title: Contact
      url: /contact

social:
    github: brianmaierjr
    twitter: brianmaierjr
    facebook: brianmaierjr
    email: brimaidesigns@gmail.com
    linkedin: brianmaierjr
    youtube: RickAstleyYT
    tumblr: i-am-a-fish

google_analytics: "UA-58263416-1"

disqus:
    shortname: brianmaierjr
